// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tenant.Infrastructure.Persistence;

#nullable disable

namespace Tenant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260904091517_AddRecordingUploadConfirmed")]
    partial class AddRecordingUploadConfirmed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tenant.Domain.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<string>("Sql")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sql");

                    b.HasKey("Id")
                        .HasName("achievements_pkey");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.AchievementContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer")
                        .HasColumnName("achievement_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("achievement_content_pkey");

                    b.HasIndex("AchievementId");

                    b.ToTable("achievement_content", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("articles_pkey");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.ArticleAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.HasKey("Id")
                        .HasName("article_attachments_pkey");

                    b.HasIndex("ArticleId");

                    b.ToTable("article_attachments", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.ArticleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id")
                        .HasName("article_categories_pkey");

                    b.ToTable("article_categories", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.ArticleCategoryAssignment", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("ArticleId", "CategoryId")
                        .HasName("article_category_assignment_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("article_category_assignment", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.ArticleCategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("article_category_id");

                    b.Property<string>("DescriptionValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_value");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("NameValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_value");

                    b.HasKey("Id")
                        .HasName("article_category_translations_pkey");

                    b.HasIndex("ArticleCategoryId");

                    b.ToTable("article_category_translations", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.ArticleTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<string>("DescriptionValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_value");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("NameValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_value");

                    b.HasKey("Id")
                        .HasName("article_translations_pkey");

                    b.HasIndex("ArticleId");

                    b.ToTable("article_translations", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.DetectedDialect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfirmedDialectId")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_dialect_id");

                    b.Property<int>("FilteredRecordingPartId")
                        .HasColumnType("integer")
                        .HasColumnName("filtered_recording_part_id");

                    b.Property<int?>("PredictedDialectId")
                        .HasColumnType("integer")
                        .HasColumnName("predicted_dialect_id");

                    b.Property<int?>("UserGuessDialectId")
                        .HasColumnType("integer")
                        .HasColumnName("user_guess_dialect_id");

                    b.HasKey("Id")
                        .HasName("detected_dialects_pkey");

                    b.HasIndex("ConfirmedDialectId");

                    b.HasIndex("UserGuessDialectId");

                    b.HasIndex(new[] { "FilteredRecordingPartId" }, "detected_dialects_filtered_part_id")
                        .IsUnique();

                    b.ToTable("detected_dialects", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_model");

                    b.Property<string>("DevicePlatform")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_platform");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fcm_token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("devices_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "FcmToken" }, "devices_fcm_token_key")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Dialect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<string>("DialectCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("dialect_code");

                    b.Property<int>("HintOrder")
                        .HasColumnType("integer")
                        .HasColumnName("hint_order");

                    b.HasKey("Id")
                        .HasName("dialects_pkey");

                    b.ToTable("dialects", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.DialectsToDo", b =>
                {
                    b.Property<string>("ConfirmedDialect")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("confirmed_dialect");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_path");

                    b.Property<DateTime?>("FilteredEndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("filtered_end_date");

                    b.Property<int?>("FilteredRecordingPartId")
                        .HasColumnType("integer")
                        .HasColumnName("filtered_recording_part_id");

                    b.Property<DateTime?>("FilteredStartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("filtered_start_date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<decimal?>("GpsLatitudeStart")
                        .HasColumnType("numeric")
                        .HasColumnName("gps_latitude_start");

                    b.Property<decimal?>("GpsLongitudeStart")
                        .HasColumnType("numeric")
                        .HasColumnName("gps_longitude_start");

                    b.Property<string>("GuessDialect")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("guess_dialect");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("ProbabilityVector")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("probability_vector");

                    b.Property<int?>("RecordingId")
                        .HasColumnType("integer")
                        .HasColumnName("recording_id");

                    b.Property<int?>("RecordingPartsId")
                        .HasColumnType("integer")
                        .HasColumnName("recording_parts_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.ToTable((string)null);

                    b.ToView("dialects_to_do", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.FilteredRecordingPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProbabilityVector")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("probability_vector");

                    b.Property<int>("RecordingId")
                        .HasColumnType("integer")
                        .HasColumnName("recording_id");

                    b.Property<bool?>("RepresentantFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("representant_flag");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short?>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("filtered_recording_parts_pkey");

                    b.HasIndex("RecordingId");

                    b.ToTable("filtered_recording_parts", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_path");

                    b.Property<string>("Format")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("format");

                    b.Property<int?>("RecordingId")
                        .HasColumnType("integer")
                        .HasColumnName("recording_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("photos_pkey");

                    b.HasIndex("RecordingId");

                    b.HasIndex("UserId");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Recording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ByApp")
                        .HasColumnType("boolean")
                        .HasColumnName("by_app");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<string>("Device")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device");

                    b.Property<short?>("EstimatedBirdsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("estimated_birds_count");

                    b.Property<int?>("ExpectedPartsCount")
                        .HasColumnType("integer")
                        .HasColumnName("expected_parts_count");

                    b.Property<bool>("Legacy")
                        .HasColumnType("boolean")
                        .HasColumnName("legacy");

                    b.Property<string>("Name")
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("NotePost")
                        .HasColumnType("text")
                        .HasColumnName("note_post");

                    b.Property<bool>("UploadConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("upload_confirmed");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("recordings_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("recordings", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.RecordingPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_path");

                    b.Property<decimal?>("GpsLatitudeEnd")
                        .HasColumnType("numeric")
                        .HasColumnName("gps_latitude_end");

                    b.Property<decimal?>("GpsLatitudeStart")
                        .HasColumnType("numeric")
                        .HasColumnName("gps_latitude_start");

                    b.Property<decimal?>("GpsLongitudeEnd")
                        .HasColumnType("numeric")
                        .HasColumnName("gps_longitude_end");

                    b.Property<decimal?>("GpsLongitudeStart")
                        .HasColumnType("numeric")
                        .HasColumnName("gps_longitude_start");

                    b.Property<int?>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<int?>("RecordingId")
                        .HasColumnType("integer")
                        .HasColumnName("recording_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("recording_parts_pkey");

                    b.HasIndex("RecordingId");

                    b.ToTable("recording_parts", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Appleid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("appleid");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("city");

                    b.Property<bool?>("Consent")
                        .HasColumnType("boolean")
                        .HasColumnName("consent");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_id");

                    b.Property<bool?>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<bool>("Legacy")
                        .HasColumnType("boolean")
                        .HasColumnName("legacy");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<int?>("PostCode")
                        .HasColumnType("integer")
                        .HasColumnName("post_code");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'user'::character varying");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Nickname" }, "users_nickname_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer")
                        .HasColumnName("achievement_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_achievement_pkey");

                    b.HasIndex("AchievementId");

                    b.HasIndex(new[] { "UserId", "AchievementId" }, "user_achievement_unique")
                        .IsUnique();

                    b.ToTable("user_achievement", (string)null);
                });

            modelBuilder.Entity("Tenant.Domain.Entities.AchievementContent", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.Achievement", "Achievement")
                        .WithMany("AchievementContents")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("achievement_content_achievement_id_fkey");

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.ArticleAttachment", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.Article", "Article")
                        .WithMany("ArticleAttachments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("article_attachments_article_fkey");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.ArticleCategoryAssignment", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.Article", "Article")
                        .WithMany("ArticleCategoryAssignments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("article_category_assignment_article_id_fkey");

                    b.HasOne("Tenant.Domain.Entities.ArticleCategory", "Category")
                        .WithMany("ArticleCategoryAssignments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("article_category_assignment_category_id_fkey");

                    b.Navigation("Article");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.ArticleCategoryTranslation", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.ArticleCategory", "ArticleCategory")
                        .WithMany("ArticleCategoryTranslations")
                        .HasForeignKey("ArticleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("article_category_translations_article_category_id_fkey");

                    b.Navigation("ArticleCategory");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.ArticleTranslation", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.Article", "Article")
                        .WithMany("ArticleTranslations")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("article_translations_article_id_fkey");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.DetectedDialect", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.Dialect", "ConfirmedDialect")
                        .WithMany("DetectedDialectConfirmedDialects")
                        .HasForeignKey("ConfirmedDialectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("detected_dialects_confirmed_dialect_id_fkey");

                    b.HasOne("Tenant.Domain.Entities.FilteredRecordingPart", "FilteredRecordingPart")
                        .WithOne("DetectedDialect")
                        .HasForeignKey("Tenant.Domain.Entities.DetectedDialect", "FilteredRecordingPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("detected_dialects_filtered_recording_part_id_fkey");

                    b.HasOne("Tenant.Domain.Entities.Dialect", "UserGuessDialect")
                        .WithMany("DetectedDialectUserGuessDialects")
                        .HasForeignKey("UserGuessDialectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("detected_dialects_user_guess_dialect_id_fkey");

                    b.Navigation("ConfirmedDialect");

                    b.Navigation("FilteredRecordingPart");

                    b.Navigation("UserGuessDialect");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Device", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.FilteredRecordingPart", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.Recording", "Recording")
                        .WithMany("FilteredRecordingParts")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("filtered_recording_parts_recording_id_fkey");

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Photo", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.Recording", "Recording")
                        .WithMany("Photos")
                        .HasForeignKey("RecordingId")
                        .HasConstraintName("photos_recording_id_fkey");

                    b.HasOne("Tenant.Domain.Entities.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_photos_user");

                    b.Navigation("Recording");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Recording", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.User", "User")
                        .WithMany("Recordings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recordings_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.RecordingPart", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.Recording", "Recording")
                        .WithMany("RecordingParts")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("recording_parts_recording_id_fkey");

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_achievement_achievement_id_fkey");

                    b.HasOne("Tenant.Domain.Entities.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_achievement_user_id_fkey");

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("AchievementContents");

                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Article", b =>
                {
                    b.Navigation("ArticleAttachments");

                    b.Navigation("ArticleCategoryAssignments");

                    b.Navigation("ArticleTranslations");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.ArticleCategory", b =>
                {
                    b.Navigation("ArticleCategoryAssignments");

                    b.Navigation("ArticleCategoryTranslations");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Dialect", b =>
                {
                    b.Navigation("DetectedDialectConfirmedDialects");

                    b.Navigation("DetectedDialectUserGuessDialects");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.FilteredRecordingPart", b =>
                {
                    b.Navigation("DetectedDialect");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.Recording", b =>
                {
                    b.Navigation("FilteredRecordingParts");

                    b.Navigation("Photos");

                    b.Navigation("RecordingParts");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Photos");

                    b.Navigation("Recordings");

                    b.Navigation("UserAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
