<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <UserSecretsId>7215c6ce-0814-42c7-af43-913dc7bd83d2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.2.1" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" Version="8.0.0-preview.3.26427.30" />
    <PackageReference Include="OpenIddict.Validation.SystemNetHttp" Version="8.0.0-preview.3.26427.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="7.3.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="7.3.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tenant.Infrastructure\Tenant.Infrastructure.csproj" />
    <ProjectReference Include="..\Tenant.Application\Tenant.Application.csproj" />
    <ProjectReference Include="..\..\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Platform.Shared\Platform.Shared.csproj" />
  </ItemGroup>

</Project>
